theme: jekyll-theme-minimal
##title: ![logo](/image/icon.png)
title: ARXIV READER
##title: Arxiv Reader - An App for consulting the Arvix database for Android - Mac-os (future)
logo: /image/icon.png
description: An App for consulting the Arvix database for Android - IOS (future)
name: ARXIV READER
github:
  is_project_page: false

